# Generated by Django 4.2.11 on 2024-03-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_images_product'),
        ('account', '0002_alter_message_receiver_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.product'),
        ),
    ]
