# Generated by Django 4.2.11 on 2024-03-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_message_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
