# Generated by Django 4.2.11 on 2024-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
