# Generated by Django 4.2.11 on 2024-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='product',
        ),
    ]
