# Generated by Django 4.2.11 on 2024-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_message_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='read_receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='read_sender',
            field=models.BooleanField(default=False),
        ),
    ]
